services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - data:/data/db

  auth:
    build:
      context: ./auth-api
      target: development
    ports:
      - '5000:5000'
    volumes:
      - ./auth-api:/app:ro
    env_file:
     - .env.local
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=secret123
      - MONGODB_HOST=mongodb
      - MONGODB_DB=users_dev
      - APP_ENV=development
    depends_on:
      - mongodb

  books:
    build:
      context: ./books-api
      target: development
    ports:
      - '5001:5001'
    volumes:
      - ./books-api:/app:ro
      - ./books-api/uploads:/app/uploads
    env_file:
     - .env.local
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=secret123
      - MONGODB_HOST=mongodb
      - MONGODB_DB=books_dev
      - APP_ENV=development
    depends_on:
      - auth

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - '3000:5173'
    volumes:
      - ./front-end:/app/:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - books
      - auth

volumes:
  data:
