services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - data:/data/db
  auth:
    build: ./auth-api
    ports:
      - '5000:5000'
    volumes:
      - ./auth-api:/app:ro
    env_file:
     - ./env/auth.env
    depends_on:
      - mongodb
  
  books:
    build: ./books-api
    ports:
      - '5001:5001'
    volumes:
      - ./books-api:/app:ro
    env_file:
     - ./env/books.env
    depends_on:
      - auth
  
  frontend:
    build: ./front-end
    ports:
      - '3000:5173'
    volumes:
      - ./front-end:/app/:ro,delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - books
      - auth

volumes:
  data:
