services:
  # mongodb:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: secret123
  #   volumes:
  #     - data:/data/db

  auth:
    build: ./auth-api
    ports:
      - '5000:5000'
    volumes:
      - ./auth-api:/app:ro
    env_file:
     - .env.local
    environment:
      - MONGODB_USERNAME=phuocnt
      - MONGODB_PASSWORD=glSn3ezpdrYLJtoD
      - MONGODB_HOST=clusterdeploy.bseek6t.mongodb.net
      - MONGODB_DB=users_dev
      - APP_ENV=production

  books:
    build: ./books-api
    ports:
      - '5001:5001'
    volumes:
      - ./books-api:/app:ro
    env_file:
     - .env.local
    environment:
      - MONGODB_USERNAME=phuocnt
      - MONGODB_PASSWORD=glSn3ezpdrYLJtoD
      - MONGODB_HOST=clusterdeploy.bseek6t.mongodb.net
      - MONGODB_DB=books_dev
      - APP_ENV=production
    depends_on:
      - auth

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
    volumes:
      - ./front-end:/app/:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - books
      - auth

volumes:
  data:
